language: node_js
node_js:
    - '10'
dist: trusty
sudo: false

branches:
    only:
        - master

cache:
    directories:
        - node_modules

script:
    - cd src
    - npx harp compile
    - npx purifycss -m src/www/stylesheets/*.css src/www/index.html > src/www/stylesheets/bundle.css
    - rm -rf src/www/stylesheets/style.css src/www/stylesheets/tachyons.min.css
    - npx sw-precache@^5 --root=www
deploy:
    repo: ClaudioCorridore/ClaudioCorridore.github.io
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: ./src/www
    target-branch: master
    on:
        branch: master
