language: node_js
node_js:
    - '10'
dist: trusty
sudo: false

branches:
    only:
        - master

cache:
    directories:
        - node_modules

script:
    - cd src
    - npx harp compile
deploy:
    repo: ClaudioCorridore/ClaudioCorridore.github.io
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: ./src/www
    target-branch: master
    on:
        branch: master
